/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package types;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SpecificExample {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SpecificExample\",\"namespace\":\"types\",\"types\":[{\"type\":\"record\",\"name\":\"Coordinates\",\"fields\":[{\"name\":\"x\",\"type\":\"float\"},{\"name\":\"y\",\"type\":\"float\"}]},{\"type\":\"record\",\"name\":\"Session\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"clicks\",\"type\":{\"type\":\"array\",\"items\":\"Coordinates\"}}]},{\"type\":\"record\",\"name\":\"Target\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"origin\",\"type\":\"Coordinates\"},{\"name\":\"radius\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Document\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"targets\",\"type\":{\"type\":\"array\",\"items\":\"Target\"}},{\"name\":\"sessions\",\"type\":{\"type\":\"array\",\"items\":\"Session\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends SpecificExample {
    public static final org.apache.avro.Protocol PROTOCOL = types.SpecificExample.PROTOCOL;
  }
}